name: verification

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/verification.yml'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  unit-tests:
    needs: [ build ]
    uses: ./.github/workflows/tests.yml
    with:
      projects: >-
        ["First.UnitTests", "Second.UnitTests"]
      coverage-threshold: 0

  functional-tests:
    needs: [ build, unit-tests ]
    uses: ./.github/workflows/tests.yml
    with:
      projects: >-
        ["First.Spec", "Second.Spec"]

  trigger-deploy:
    needs: [ build, unit-tests, functional-tests ]
    name: 📈 Trigger deploy workflow
    uses: ./.github/workflows/deploy.yml
