name: verification

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/verification.yml'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: [ build ]
    uses: ./.github/workflows/tests.yml
    with:
      projects: >-
        ["First", "Second"]
      test-types: >-
        [
          {
            type: "UnitTests",
            coverageThreshold: 90
          },
          {
            type: "Spec",
            coverageThreshold: 20
          },
        ]

  trigger-deploy:
    needs: [ test ]
    name: 📈 Trigger deploy workflow
    uses: ./.github/workflows/deploy.yml
